spring:
  datasource:
    url: ${prod.db.url}
    username: ${prod.db.username}
    password: ${prod.db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false

decorator:
  datasource:
    p6spy:
      enable-logging: false

logging:
  level:
    kr.flint: info